data <- read.table("household_power_consumption.txt",sep=";",header=T,stringsAsFactors=F, na.strings="?")
data$Date <- as.Date(data$Date, "%d/%m/%Y")
subdata<-subset(data,data$Date=="2007-02-01"|data$Date=="2007-02-02")
subdata$Global_active_power<-as.numeric(subdata$Global_active_power)
datetime<-paste(subdata$Date,subdata$Time)
datetime<-as.POSIXct(datetime)
png(file="plot2.png")
par(pin=c(5,5))
plot(datetime,subdata$Global_active_power,type = "l",lty=1,xlab=" ",ylab="Global Active Power (kilowatts)")
dev.off()