data <- read.table("household_power_consumption.txt",sep=";",header=T,stringsAsFactors=F, na.strings="?")
data$Date <- as.Date(data$Date, "%d/%m/%Y")
subdata<-subset(data,data$Date=="2007-02-01"|data$Date=="2007-02-02")
subdata$Global_active_power<-as.numeric(subdata$Global_active_power)
datetime<-paste(subdata$Date,subdata$Time)
datetime<-as.POSIXct(datetime)
png(file="plot3.png")
par(pin=c(5,5))
plot(datetime,subdata$Sub_metering_1,type = "l",lty=1,xlab=" ",ylab="Energy sub metering")
lines(datetime,subdata$Sub_metering_2, col = "red")
lines(datetime,subdata$Sub_metering_3, col = "blue")
legend("topright",lty = 1,col = c("black","red","blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()