data <- read.table("household_power_consumption.txt",sep=";",header=T,stringsAsFactors=F, na.strings="?")
data$Date<-as.Date(data$Date, "%d/%m/%Y")
subdata<-subset(data,data$Date=="2007-02-01"|data$Date=="2007-02-02")
subdata$Global_active_power<-as.numeric(subdata$Global_active_power)
png(file="plot1.png")
hist(subdata$Global_active_power, col="red",main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.off()